<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Character</title>
    <link rel="stylesheet" href="<?=SITE_ROOT?>/css/characterStyle.css">
    <!-- <script src="js/script.js"></script> -->
  </head>
  <body>
    <div id="siteContainer">
      <div id="site">
        <div id="headingContainer">
        </div>
        <div id="menuContainer">
        </div>
        <div id="contentContainer">
        	<?php echo $_controller->vars->content; ?>
        </div>
        <div id="footerContainer">
        </div>
      </div>
    </div>
  </body>
</html>
