<?php
$characterProvider = new Model_Data_CharacterProvider();
$newChars = $characterProvider->getNewChars(5);
?>
	<div id="nc_container">
		<div id="nc_head"></div>
		<div id="nc_content_frame">
			<div id="nc_content">
				<div id="nc_inner">
					<?php foreach($newChars as $char): ?>
	                <p class="new_char"><a href="<?=SITE_ROOT . "/character/view/" . $char['name'] ?>"><?=$char['name']?></a><br>&nbsp;&nbsp;(<?=$char['username']?>)</p>
	                <?php endforeach; ?>
				</div>
			</div>
		</div>
		<div id="nc_foot"></div>
	</div>
